### ISSUE TITLE
ModelJoin Language Asset and MeterAsset in Task2

### ISSUE THREAD

**Issue by SvenPeldszus** [georghinkel/ttc2017smartGrids#10]
Hello, I've a problem to understand, what exactly happens with the `Asset` and `MeterAsset` in the given ModelJoin specification.

In line 1 I am joining a `MeterAsset` with a `MMXU` to a `jointarget.PMUVoltageMeter`. But then I am transforming any Asset into an `jointarget.Asset`. What does this mean for the `MeterAsset`s transformed in  line 1?

Should I translate all `MeterAsset`s, which have been translated in line 1, again or only the not translated `Asset`s. 

If the second option is the right one. Do all following keep operations only apply to the `Asset`s translated in line 15 or also to the `MeterAsset`s translated in line 1?

**Comment by georghinkel** [comment]
Hi Sven,

the `keep supertype` declaration basically defines that the base type `Asset` should also be contained in the view type as type `Asset`. It does not mean that all assets should be transformed, still only the `MeterAsset`s. The fact that the following declarations are in braces is only relevant for extracting the view type from the view specification, which is also done by ModelJoin.

However, in the scope of the benchmark, the extraction of the view type is irrelevant because the viewtype is already given (in the metamodels directory). Therefore, you can safely ignore `keep supertype` declarations - they give you an information in which class an attribute or reference is located, but that information is usually not important.

Hope that helps,

Georg

**Comment by SvenPeldszus** [comment]
Hi Georg,

thanks for the clarification.

Best regards,

Sven
